import json

name = input("Enter hero name id: ")
level = int(input("How many boons does your hero have? (0-35): "))

with open("data/hero-data.json", "r") as file:
    data = json.load(file)

# hero stats to display
spirit_power = 0 + (data.get(name, {}).get("LevelScaling", {}).get("TechPower", 0) * level)

bullet_damage = data.get(name, {}).get("Weapon", {}).get("BulletDamage", 0) + (data.get(name, {}).get("LevelScaling", {}).get("BulletDamage", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("BulletDamage", 0) * spirit_power)
ammo = data.get(name, {}).get("Weapon", {}).get("ClipSize", 0) + (data.get(name, {}).get("LevelScaling", {}).get("ClipSize", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("ClipSize", 0) * spirit_power)
rounds_per_second = data.get(name, {}).get("Weapon", {}).get("RoundsPerSecond", 0) + (data.get(name, {}).get("LevelScaling", {}).get("RoundsPerSecond", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("RoundsPerSecond", 0) * spirit_power)
reload_time = data.get(name, {}).get("Weapon", {}).get("ReloadTime", 0) + (data.get(name, {}).get("LevelScaling", {}).get("ReloadTime", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("ReloadTime", 0) * spirit_power)
bullet_velocity = data.get(name, {}).get("Weapon", {}).get("BulletSpeed", 0) + (data.get(name, {}).get("LevelScaling", {}).get("BulletSpeed", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("BulletSpeed", 0) * spirit_power)
light_melee_damage = data.get(name, {}).get("LightMeleeDamage", 0) + (data.get(name, {}).get("LevelScaling", {}).get("LightMeleeDamage", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("LightMeleeDamage", 0) * spirit_power)
heavy_melee_damage = data.get(name, {}).get("HeavyMeleeDamage", 0) + (data.get(name, {}).get("LevelScaling", {}).get("HeavyMeleeDamage", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("HeavyMeleeDamage", 0) * spirit_power)

health = data.get(name, {}).get("MaxHealth", 0) + (data.get(name, {}).get("LevelScaling", {}).get("MaxHealth", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("MaxHealth", 0) * spirit_power)
health_regen = data.get(name, {}).get("BaseHealthRegen", 0) + (data.get(name, {}).get("LevelScaling", {}).get("BaseHealthRegen", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("BaseHealthRegen", 0) * spirit_power)
bullet_resist = data.get(name, {}).get("BulletResist", 0) + (data.get(name, {}).get("LevelScaling", {}).get("BulletResist", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("BulletResist", 0) * spirit_power)
spirit_resist = data.get(name, {}).get("SpiritResist", 0) + (data.get(name, {}).get("LevelScaling", {}).get("SpiritResist", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("SpiritResist", 0) * spirit_power)
move_speed = data.get(name, {}).get("MaxMoveSpeed", 0) + (data.get(name, {}).get("LevelScaling", {}).get("MaxMoveSpeed", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("MaxMoveSpeed", 0) * spirit_power)
sprint_speed = data.get(name, {}).get("SprintSpeed", 0) + (data.get(name, {}).get("LevelScaling", {}).get("SprintSpeed", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("SprintSpeed", 0) * spirit_power)
dash_speed_ground = data.get(name, {}).get("GroundDashSpeed", 0) + (data.get(name, {}).get("LevelScaling", {}).get("GroundDashSpeed", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("GroundDashSpeed", 0) * spirit_power)
dash_speed_air = data.get(name, {}).get("AirDashSpeed", 0) + (data.get(name, {}).get("LevelScaling", {}).get("AirDashSpeed", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("AirDashSpeed", 0) * spirit_power)
stamina = data.get(name, {}).get("Stamina", 0) + (data.get(name, {}).get("LevelScaling", {}).get("Stamina", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("Stamina", 0) * spirit_power)
stamina_regen = data.get(name, {}).get("StaminaCooldown", 0) + (data.get(name, {}).get("LevelScaling", {}).get("StaminaCooldown", 0) * level) + (data.get(name, {}).get("SpiritScaling", {}).get("StaminaCooldown", 0) * spirit_power)

print("Hero Name: ", data[name]["Name"])
print("-----")
print("Bullet Damage: " + str(bullet_damage))
print("Ammo: ", str(ammo))
print("Rounds Per Second: ", str(rounds_per_second))
print("Reload Time: ", str(reload_time))
print("Bullet Velocity: ", str(bullet_velocity))
print("Light Melee Damage: " + str(light_melee_damage))
print("Heavy Melee Damage: " + str(heavy_melee_damage))
print("-----")
print("Health: " + str(health))
print("Health Regen: ", str(health_regen))
print("Bullet Resist: " + str(bullet_resist))
print("Spirit Resist: " + str(spirit_resist))
print("Move Speed: ", str(move_speed))
print("Sprint Speed: ", str(sprint_speed))
print("Dash Speed (Ground): ", str(dash_speed_ground))
print("Dash Speed (Air): ", str(dash_speed_air))
print("Stamina: ", str(stamina))
print("Stamina Regen: ", str(stamina_regen))
print("-----")
print("Spirit Power: " + str(spirit_power))
